
name: Test Action

on:
  push:
    paths:
      - '.github/**'
      - action.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ebitkov/build-symfony-bundle@main
        with:
          repository: ebitkov/symfony-bundle
